### ISSUE TITLE
[3.x] Feedback: Concurrency & Pools slower than in v2

### ISSUE THREAD

**Issue by SamuelMwangiW** [Sammyjo20/Saloon#306] opened 2023-10-05 19:27 UTC
Thanks so much Sam for the incredible work you do. 

This is not of a bug report report but general feedback after playing around with v3. 

I understand that the cause may be the design decision to lean more into the building and use of PSR-7 requests as opposed to use Guzzle's configuration options for v3.

I observed this after a version of the test below started failing upon upgrading to v3. The same benchmark is taking approx 4X more time in v3 than v2.

```PHP
test('benchmark pooling requests', function (string $phone): void {
    $count = 1_000;
    $expectedTime = 30_000;

    $messages = collect(fake()->sentences($count));

    $responses = collect([]);

    $requests = $messages->map(function (string $message) use ($phone): SmsRequest {
        return SmsRequest::make([
            'message' => $message,
            'to' => $phone,
            'from' => config(key: 'provider.from'),
        ]);
    });

    $connector = MyConnector::make();

    $timeInMilliseconds = Benchmark::measure(
        fn () => $connector->pool(
            requests: $requests,
            concurrency: 10,
            responseHandler: fn (Response $data) => $responses->push($data->dto())
        )->send()->wait()
    );

    expect($timeInMilliseconds)->toBeLessThan($expectedTime); //Less than 30 Seconds to send 1000 messages
})->with('phone-numbers');
```

I know that the above is a really extreme example but that's speaks more to how impressive concurrency is. I will take a bit more time to run more tests and try drilling down the root cause of the increased execution times.

Thanks once again and happy coding 🤠

**Comment by Sammyjo20** [comment] 2023-10-05 21:13
Hey @SamuelMwangiW 

Thank you for your kind words and thank you so much for raising this issue with me and providing an example. There was a point a couple of days ago when I was using pools and thought "Hm, there's no speed difference" but I shook it off and thought it was an internet issue. I'll get a testbench setup on my machine and try to replicate the issue.

I think it might be something to do with the promise wrapping that I'm now doing in v3 as I believe Guzzle should still be able to send requests concurrently even if they're a PSR-7 request that Saloon has built - I may be wrong though. 

Again thank you and I'll get back to you once I've done some testing 👍

**Comment by Sammyjo20** [comment] 2023-10-05 21:25
Quick update: I was able to replicate it... 🙈 So sending 100 requests:

v2 - 900ms (average of 3 runs)
v3 - 7 seconds (average of 3 runs)

I will sort this! 🤠

Update: I've confirmed it is the nested Promises that I wrote - when I return the Guzzle promise directly I get the superfast speeds again. I'll see if I can get the nested promises working properly - maybe I didn't implement them right!

**Comment by Sammyjo20** [comment] 2023-10-05 21:48
So the issue lies in the `SendsRequests.php` trait. This is the following code that is causing all the trouble:

Specifically the first and last lines where I define the nested promise and resolve it.

```php
return $promise = new Promise(function () use (&$promise, $request, $mockClient, $sender) {
    $pendingRequest = $this->createPendingRequest($request, $mockClient)->setAsynchronous(true);

    // We need to check if the Pending Request contains a fake response.
    // If it does, then we will create the fake response. Otherwise,
    // we'll send the request.

    // 🚀 ... 🪐  ... 💫

    if ($pendingRequest->hasFakeResponse()) {
        $requestPromise = $this->createFakeResponse($pendingRequest);
    } else {
        $requestPromise = $sender->sendAsync($pendingRequest);
    }

    $requestPromise->then(fn (Response $response) => $pendingRequest->executeResponsePipeline($response));

    // We'll resolve the promise's value with another promise.
    // We will use promise chaining as Guzzle's will fulfill
    // the request promise.

    return $promise->resolve($requestPromise);
});
```

The code inside isn't an issue because it will work if I change it to this - and the speed will go back up!

```php
$pendingRequest = $this->createPendingRequest($request, $mockClient)->setAsynchronous(true);

// We need to check if the Pending Request contains a fake response.
// If it does, then we will create the fake response. Otherwise,
// we'll send the request.

// 🚀 ... 🪐  ... 💫

if ($pendingRequest->hasFakeResponse()) {
    $requestPromise = $this->createFakeResponse($pendingRequest);
} else {
    $requestPromise = $sender->sendAsync($pendingRequest);
}

$requestPromise->then(fn (Response $response) => $pendingRequest->executeResponsePipeline($response));

return $requestPromise;
```

I wrote the wrapper promise because I didn't want the `PendingRequest` to be created until the promise was actually being handled. I'd love to keep this functionality - maybe there's someone out there that knows promises better than I do.

https://github.com/guzzle/promises

**Comment by SamuelMwangiW** [comment] 2023-10-05 22:58
Thanks @Sammyjo20 for taking the time to look into the issue. Am really glad you were able to quickly replicate the issue.

**Comment by Sammyjo20** [comment] 2023-10-06 16:48
Alright so I'm back at the laptop again trying to debug this and this is my latest theory...

The `EachPromise` that is used inside of Saloon's `Pool` class is queueing up all of the promises and resolving them in the concurrency - in my example 10 promises at once. It's then going inside my nested promise and just running resolve - which is instant, but it's not running the inner promise (the request promise) at the same time, it is separately queueing them which then runs at the normal concurrency and just waits until each request has been sent. 

I need to somehow tell Guzzle to invoke the inner promise at the same time. I've tried doing

```php
$promise->resolve($requestPromise->wait());
```

But that didn't work either 🤔

**Comment by aidan-casey** [comment] 2023-10-06 17:30
@Sammyjo20 What happens if you change it to the following?

```php
$promise = new Promise(function () use (&$promise, $request, $mockClient, $sender) {
    $promise->resolve(null);
});

$promise
    ->then(function() use ($request, $mockClient, $sender) {
        $pendingRequest = $this->createPendingRequest($request, $mockClient)->setAsynchronous(true);

        // We need to check if the Pending Request contains a fake response.
        // If it does, then we will create the fake response. Otherwise,
        // we'll send the request.

        // 🚀 ... 🪐  ... 💫

        if ($pendingRequest->hasFakeResponse()) {
            $requestPromise = $this->createFakeResponse($pendingRequest);
        } else {
            $requestPromise = $sender->sendAsync($pendingRequest);
        }

        $requestPromise->then(fn (Response $response) => $pendingRequest->executeResponsePipeline($response));
        
        return $requestPromise;
    });
```

**Comment by Sammyjo20** [comment] 2023-10-06 17:54
Hey @aidan-casey thank you for helping ❤️

So if I run it like this: 


```php
$promise = new Promise(function () use (&$promise, $request, $mockClient, $sender) {
    $promise->resolve(null);
});

$promise
    ->then(function() use ($request, $mockClient, $sender) {
        $pendingRequest = $this->createPendingRequest($request, $mockClient)->setAsynchronous(true);

        // We need to check if the Pending Request contains a fake response.
        // If it does, then we will create the fake response. Otherwise,
        // we'll send the request.

        // 🚀 ... 🪐  ... 💫

        if ($pendingRequest->hasFakeResponse()) {
            $requestPromise = $this->createFakeResponse($pendingRequest);
        } else {
            $requestPromise = $sender->sendAsync($pendingRequest);
        }

        $requestPromise->then(fn (Response $response) => $pendingRequest->executeResponsePipeline($response));

        return $requestPromise;
    });

return $promise;
```

It will run in 100ms and pretty much do nothing. 

If I do this:

```php
$promise = new Promise(function () use (&$promise, $request, $mockClient, $sender) {
    $promise->resolve(null);
});

return $promise
    ->then(function() use ($request, $mockClient, $sender) {
        $pendingRequest = $this->createPendingRequest($request, $mockClient)->setAsynchronous(true);

        // We need to check if the Pending Request contains a fake response.
        // If it does, then we will create the fake response. Otherwise,
        // we'll send the request.

        // 🚀 ... 🪐  ... 💫

        if ($pendingRequest->hasFakeResponse()) {
            $requestPromise = $this->createFakeResponse($pendingRequest);
        } else {
            $requestPromise = $sender->sendAsync($pendingRequest);
        }

        $requestPromise->then(fn (Response $response) => $pendingRequest->executeResponsePipeline($response));

        return $requestPromise;
    });
```

It will take 7 seconds again 🤔

**Comment by aidan-casey** [comment] 2023-10-06 18:31
I think you are on the right track with your thinking on the queue. I'm not at my computer at the moment, but would be curious to play a little bit.

Just by way of clarification, what is the goal with wrapping it in a promise? You are deferring the creation of the pending request until a certain point anyway by having it in a method that is called by the pool `send`, so all this set up work gets done almost instantly anyway, right?

**Comment by Sammyjo20** [comment] 2023-10-06 18:35
Yep! I would love it if the `PendingRequest` and middleware would run when the request was just about to be sent rather than in v2 it would run the middleware and then queue the request. I think you're on the right track with this promise forwarding - I can also push up my testbench if you need to play around with it.

**Comment by Sammyjo20** [comment] 2023-10-06 18:38
I've pushed up for you @aidan-casey. You can test it by running this example test that hits my test server. Feel free to play around. I was just modifying the `SendsRequests.php` in my vendor file.

https://github.com/Sammyjo20/saloon-testbench/blob/main/tests/Feature/ExampleTest.php

**Comment by Sammyjo20** [comment] 2023-10-07 07:14
Okay so I've still not been able to work this one out - but I am wondering if it is something we can resolve or not. I had a look at Guzzle's logic and I've worked out that Guzzle will invoke all of its middleware before the request is sent. Guzzle doesn't invoke the middleware while the promise is being resolved.

See below. I created a Guzzle request middleware that output "Send!" as you can see it invokes 10 of them before getting a response.

<img width="421" alt="Screenshot 2023-10-07 at 08 03 43" src="https://github.com/saloonphp/saloon/assets/29132017/d76efc4f-c6d0-4f09-b660-533ed494a9fe">

So, I would be happy to change Saloon's implementation back to the way it worked in v2 when we didn't wrap the promise inside another promise. It's a bit of a shame because it was a cool feature that should work - but the way Guzzle internally wraps promises I'm not sure it's something we can reliably do. I know it's only been a day or two so I think it's worth keep looking over the weekend.

**Comment by Sammyjo20** [comment] 2023-10-07 18:26
Hey @SamuelMwangiW I believe I managed to fix the issue in #308! Would you mind updating to v3.0.1 (composer update should do) and test it again please? Let me know your findings - but hopefully this would have fixed it while having the benefit of keeping it wrapped in a promise 🙌

**Comment by SamuelMwangiW** [comment] 2023-10-07 19:00
Thanks so much @Sammyjo20. 

I can confirm that the above benchmark is now taking an average of 21 seconds to run which is a significant improvement from when I opened the issue.

Thanks once again for the incredible work you do 👏🏽

**Comment by Sammyjo20** [comment] 2023-10-07 19:02
That's awesome @SamuelMwangiW so just to confirm what kind of times were you getting before the fix?

**Comment by SamuelMwangiW** [comment] 2023-10-07 19:12
The benchmark to send 1000 messages was taking approx 2 min before the fix which I knew couldn't be explained by a difference in internet speeds.

**Comment by Sammyjo20** [comment] 2023-10-07 19:13
Wow, what a difference! Amazing, well I am so glad that this seemingly impossible issue to fix was not impossible 🔥 Have a great day!

**Closed as completed by Sammyjo20** 2023-10-07 19:13 UTC
Labels: bug
